# Generated by Django 5.2.9 on 2025-12-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('movies', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('no_of_movies', models.IntegerField()),
            ],
        ),
    ]
